# DISABLED WORKFLOW
#
# This file was moved out of `.github/workflows/` to avoid running and to avoid editor
# workflow diagnostics in local environments. It is kept only as reference.
#
# NOTE: The current Next.js app is not configured as a static export (`out/`), so this
# SFTP approach is likely not appropriate unless the project is converted to a static build.

name: Deploy to GoDaddy (SFTP) [DISABLED]

on:
  workflow_dispatch:

env:
  SFTP_HOST: ${{ secrets.SFTP_HOST }}
  SFTP_USER: ${{ secrets.SFTP_USER }}
  SFTP_PASSWORD: ${{ secrets.SFTP_PASSWORD }}
  SFTP_PORT: ${{ secrets.SFTP_PORT }}
  SFTP_SSH_PRIVATE_KEY: ${{ secrets.SFTP_SSH_PRIVATE_KEY }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install
        run: npm ci

      - name: Build (static export)
        run: npm run build

      - name: Upload artifact (out)
        uses: actions/upload-artifact@v4
        with:
          name: site-out
          path: out

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: ${{ github.ref == 'refs/heads/main' }}
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: site-out
          path: out

      - name: Deploy via SFTP to GoDaddy
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          server: ${{ env.SFTP_HOST }}
          username: ${{ env.SFTP_USER }}
          password: ${{ env.SFTP_PASSWORD }}
          ssh_private_key: ${{ env.SFTP_SSH_PRIVATE_KEY }}
          port: ${{ env.SFTP_PORT != '' && env.SFTP_PORT || '22' }}
          local_path: 'out/*'
          remote_path: 'public_html/'
          delete_remote_files: false
          sftpArgs: '-o StrictHostKeyChecking=no'
