name: Deploy to GoDaddy (SFTP)

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install
        run: npm ci

      - name: Build (static export)
        run: npm run build

      - name: Upload artifact (out)
        uses: actions/upload-artifact@v4
        with:
          name: site-out
          path: out

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: ${{ github.ref == 'refs/heads/main' }}
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: site-out
          path: out

      - name: Deploy via SFTP to GoDaddy
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          server: ${{ secrets.SFTP_HOST }}
          username: ${{ secrets.SFTP_USER }}
          password: ${{ secrets.SFTP_PASSWORD }}
          port: ${{ secrets.SFTP_PORT || 22 }}
          local_path: 'out/*'
          remote_path: 'public_html/'
          delete_remote_files: false
          sftpArgs: '-o StrictHostKeyChecking=no'
